### ISSUE TITLE
problem regarding 'mila init'

### ISSUE THREAD

**Issue by PwnerHarry** [mila-iqia/milatools#1]
$ mila init
Checking ssh config
Traceback (most recent call last):
  File "/home/pharry/ENV/bin/mila", line 8, in <module>
    sys.exit(main())
  File "/home/pharry/ENV/lib/python3.8/site-packages/milatools/commands.py", line 13, in main
    auto_cli(milatools)
  File "/home/pharry/ENV/lib/python3.8/site-packages/coleo/cli.py", line 611, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "/home/pharry/ENV/lib/python3.8/site-packages/coleo/cli.py", line 583, in run_cli
    return call(opts=opts, args=args)
  File "/home/pharry/ENV/lib/python3.8/site-packages/coleo/cli.py", line 542, in thunk
    result = fn(*args)
  File "/home/pharry/ENV/lib/python3.8/site-packages/ptera/core.py", line 853, in __call__
    rval = super().__call__(*self.partial_args, *args, **kwargs)
  File "/home/pharry/ENV/lib/python3.8/site-packages/ptera/selfless.py", line 656, in __call__
    return self.fn(self, *args, **kwargs)
  File "/home/pharry/ENV/lib/python3.8/site-packages/milatools/commands.py", line 41, in init
    c = SSHConfig()
  File "/home/pharry/ENV/lib/python3.8/site-packages/milatools/utils.py", line 137, in __init__
    self.cfg = read_ssh_config(os.path.expanduser("~/.ssh/config"))
  File "/home/pharry/ENV/lib/python3.8/site-packages/sshconf.py", line 367, in read_ssh_config
    master_config = read_ssh_config_file(master_path)
  File "/home/pharry/ENV/lib/python3.8/site-packages/sshconf.py", line 121, in read_ssh_config_file
    with open(path, "r") as fh_:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pharry/.ssh/config'

**Comment by breuleux** [comment]
Just so we're clear, is the issue that there is no SSH config in that environment, or is it that there is one, but it's in a different location than the standard `~/.ssh/config`? What is the OS? Is this a VM or container?

**Comment by PwnerHarry** [comment]
This is a WSL2 Ubuntu with no ssh history

**Comment by breuleux** [comment]
I pushed a fix that should create `~/.ssh/config` if it does not exist. I also fixed an issue with the fingerprint prompt if the login nodes aren't already in `known_hosts`.

Can you try again and tell me if there are any more issues? Thanks for the feedback :)

**Comment by breuleux** [comment]
Note: I made a mistake in setting the permissions for `.ssh`, so use 0.0.3.

**Comment by PwnerHarry** [comment]
I think the initialization is now fine. However I am not sure how to use the python interpreter on the cluster.

**Comment by breuleux** [comment]
Assuming you have the Python extension installed, you can follow [these instructions](https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment) to select an interpreter, and then you can run and debug the current file, etc.

If you have a normal shell from `ssh mila` where you already activated the environment you want to use, you can run `which python` and then copy paste the output into "select an interpreter" in VSCode. I *think* it might remember it the next time you run VSCode in that directory, but I'm not sure.

**Comment by PwnerHarry** [comment]
When i browse for my venvs, i see only the local ubuntu file system...

**Comment by breuleux** [comment]
Using `mila code path/to/directory`? What's the command's output? The VSCode window should have SSH in the title bar and in the bottom-left corner.

**Comment by PwnerHarry** [comment]
It seems there was a connection refused error:

```
$ mila code .
(local) $ ssh mila -fNMS /home/pharry/.ssh/sockets/milatools.mila
(mila) $ salloc
# Control socket connect(/home/pharry/.ssh/sockets/milatools.mila): Connection refused
# salloc: --------------------------------------------------------------------------------------------------
# salloc: # CPU-job in low priority
# salloc: --------------------------------------------------------------------------------------------------
# salloc: Granted job allocation 1083618
# salloc: Waiting for resource configuration
# salloc: Nodes kepler3 are ready for job
(mila) $ echo $HOME
Control socket connect(/home/pharry/.ssh/sockets/milatools.mila): Connection refused
# /home/mila/z/zhaoming
(local) $ code --remote ssh-remote+kepler3.server.mila.quebec /home/mila/z/zhaoming/.
```

**Comment by breuleux** [comment]
That error doesn't seem to matter, the node was allocated regardless.

It seems to behave a bit weird with `mila code .`, but if you open the sidebar you should be able to browse to a local folder. `mila code ""` might work a little better.

**Comment by PwnerHarry** [comment]
I tried the VS with a real path however it seems my vs cannot connect normally. I thought that was because I was using WSL2, so I switched to my Windows for a "mila init". However:

```
PS C:\Users\H> mila init
Checking ssh config
# OK
Checking passwordless authentication
(local) $ ssh -oPreferredAuthentications=publickey mila 'echo OK'
# OK
Checking connection to compute nodes
(local) $ ssh mila -fNMS 'C:\Users\H/.ssh/sockets\milatools.mila'
(mila) $ ls -t ~/.ssh/id*.pub
getsockname failed: Bad file descriptor
channel_send_open: channel 0: unexpected internal error
# MISSING
You have no public keys on the login node. Generate them? [Y/n]
```
the cmd would remain stuck forever

**Comment by breuleux** [comment]
The mix of `/` and `\` in the path probably isn't helping, but I doubt it'd work in plain Windows either way. I don't have any Windows machines to test, though.
