### ISSUE TITLE
[v0.1.5] Issue running the command `mila init`

### ISSUE THREAD

**Issue by alzambranolu13** [mila-iqia/milatools#129]
### What command did you run?
mila init

### Describe the bug
When introducing password after mila init command I get following traceback.
```
Connection closed by 172.16.2.25 port 2222
Traceback (most recent call last):
  File "/home/alejandra/anaconda3/lib/python3.12/site-packages/milatools/cli/commands.py", line 89, in main
    mila()
  File "/home/alejandra/anaconda3/lib/python3.12/site-packages/milatools/cli/commands.py", line 146, in mila
    return function(**args_dict)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/anaconda3/lib/python3.12/site-packages/milatools/cli/commands.py", line 529, in init
    success = setup_passwordless_ssh_access(ssh_config=ssh_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/anaconda3/lib/python3.12/site-packages/milatools/cli/init_command.py", line 256, in setup_passwordless_ssh_access
    success = setup_passwordless_ssh_access_to_cluster("mila")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/anaconda3/lib/python3.12/site-packages/milatools/cli/init_command.py", line 347, in setup_passwordless_ssh_access_to_cluster
    here.run(
  File "/home/alejandra/anaconda3/lib/python3.12/site-packages/milatools/utils/local_v1.py", line 47, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/home/alejandra/anaconda3/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('ssh-copy-id', '-i', '/home/alejandra/.ssh/id_rsa', '-o', 'StrictHostKeyChecking=no', 'mila')' returned non-zero exit status 1.
```

### Desktop
 - OS: Ubuntu 24.04
### Additional context
Everytime I try to connect to any cluster via ssh <user>@login.server.mila.quebec -p 2222 
I get  `ssh <user>@login.server.mila.quebec -p 2222`

**Comment by lebrice** [comment]
Hey there @alzambranolu13 , is this issue still happening for you?
