### ISSUE TITLE
[v0.1.6] Issue running the command `mila init`

### ISSUE THREAD

**Issue by wenhao-mila** [mila-iqia/milatools#140]
### What command did you run?
`mila init`

### Describe the bug

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/milatools/cli/commands.py", line 89, in main
    mila()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/milatools/cli/commands.py", line 146, in mila
    return function(**args_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/milatools/cli/commands.py", line 529, in init
    success = setup_passwordless_ssh_access(ssh_config=ssh_config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/milatools/cli/init_command.py", line 256, in setup_passwordless_ssh_access
    success = setup_passwordless_ssh_access_to_cluster("mila")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/milatools/cli/init_command.py", line 313, in setup_passwordless_ssh_access_to_cluster
    assert ssh_public_key_path.exists()
AssertionError

### Screenshots
<img width="594" alt="Screenshot 2024-12-20 at 14 29 18" src="https://github.com/user-attachments/assets/22f17e9d-3d05-4eea-acb0-091ff2561735" />
<img width="582" alt="Screenshot 2024-12-20 at 14 30 51" src="https://github.com/user-attachments/assets/9d441abe-712d-4bf7-b7f9-0792c9421eea" />

### Desktop (please complete the following information):
 - Mac OS 14.4.1

**Comment by wenhao-mila** [comment]
Fixed by manually adding SSH keys `id_rsa` and `id_rsa.pub` on the server
