### ISSUE TITLE
Issue with the "--persist" option

### ISSUE THREAD

**Issue by leogagnon** [mila-iqia/milatools#39]
### What command did you run?
mila code --persist .

### Describe the bug
<pre><code>
Traceback (most recent call last):
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/commands.py", line 42, in main
    auto_cli(milatools)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/coleo/cli.py", line 656, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/commands.py", line 314, in code
    data, proc = cnode.ensure_allocation()
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/remote.py", line 251, in ensure_allocation
    proc, results = self.extract(
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/remote.py", line 139, in extract
    proc = self.run(cmd, asynchronous=True, out_stream=qio, **kwargs)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/remote.py", line 127, in run
    cmd = transform(cmd)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/remote.py", line 234, in srun_transform_persist
    self.puttext(batch, batch_file)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/remote.py", line 178, in puttext
    self.put(f.name, dest)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/milatools/cli/remote.py", line 170, in put
    return self.connection.put(src, dest)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/fabric/connection.py", line 870, in put
    return Transfer(self).put(*args, **kwargs)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/fabric/transfer.py", line 311, in put
    self.sftp.put(localpath=local, remotepath=remote)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/paramiko/sftp_client.py", line 759, in put
    return self.putfo(fl, remotepath, file_size, callback, confirm)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/paramiko/sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/Users/leogagnon/.pyenv/versions/3.9.16/lib/python3.9/site-packages/paramiko/sftp_client.py", line 907, in _convert_status
    raise IOError(text)
OSError: Failure
</code></pre>

### System information
 - macOS 13.2.1
 - M1 pro
 - python 3.9.16

### Additional information
Works fine without the "--persist" option

**Comment by leogagnon** [comment]
Solved. It was caused by my home folder being full.
