### ISSUE TITLE
ValueError when running 'mila init' 

### ISSUE THREAD

**Issue by hugobb** [mila-iqia/milatools#4]
When running 'mila init' I get the following error:
```
$ mila init
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py3.8/bin/mila", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/milatools/commands.py", line 14, in main
    auto_cli(milatools)
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/coleo/cli.py", line 613, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/coleo/cli.py", line 584, in run_cli
    opts, call = make_cli(entry, **kwargs)
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/coleo/cli.py", line 534, in make_cli
    _make_cli_helper(parser, entry, tag=tag, eval_env=eval_env, extras=extras)
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/coleo/cli.py", line 460, in _make_cli_helper
    entry2 = tooled(entry2)
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/ptera/deco.py", line 55, in __call__
    new_fn, state = transform(fn, interact=interact)
  File "/opt/miniconda3/envs/py3.8/lib/python3.9/site-packages/ptera/selfless.py", line 510, in transform
    new_fn = compile(
ValueError: field 'id' is required for Name
```

Details:
- macOS Big Sur 11.6
- python 3.9.7
- milatools 0.0.5

**Comment by breuleux** [comment]
Apologies for not seeing this sooner, I thought I was watching this repo but I wasn't 😅 

I pinned working versions, so it should work now if you update.
