### ISSUE TITLE
[v0.0.17] Issue running the command `mila code`

### ISSUE THREAD

**Issue by KihoCho0627** [mila-iqia/milatools#44]
### Make sure you can reproduce the issue with the latest version available
```
pip install milatools --upgrade
[milatools command e.g. mila code ...]
```

Yes I did

### What command did you run?
[e.g. `mila code ...`]
mila code Research/DomainGeneralization --alloc --gres=gpu:1 -c 4 --mem=24000

### Describe the bug
A clear and concise description of what the bug is. If there is an error
traceback, please paste it here.

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\site-packages\milatools\cli\commands.py", line 43, in main
    auto_cli(milatools)
  File "C:\ProgramData\miniconda3\lib\site-packages\coleo\cli.py", line 656, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "C:\ProgramData\miniconda3\lib\site-packages\coleo\cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "C:\ProgramData\miniconda3\lib\site-packages\coleo\cli.py", line 587, in thunk
    result = fn(*args)
  File "C:\ProgramData\miniconda3\lib\site-packages\milatools\cli\commands.py", line 285, in code
    remote = Remote("mila")
  File "C:\ProgramData\miniconda3\lib\site-packages\milatools\cli\remote.py", line 84, in __init__
    connection.open()
  File "C:\ProgramData\miniconda3\lib\site-packages\fabric\connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\client.py", line 459, in connect
    self._auth(
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\client.py", line 717, in _auth
    self._agent = Agent()
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\agent.py", line 406, in __init__
    self._connect(conn)
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\agent.py", line 79, in _connect
    ptype, result = self._send_message(cSSH2_AGENTC_REQUEST_IDENTITIES)
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\agent.py", line 96, in _send_message
    self._conn.send(struct.pack(">I", len(msg)) + msg)
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\win_pageant.py", line 126, in send
    self._response = _query_pageant(data)
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\win_pageant.py", line 93, in _query_pageant
    pymap.write(msg)
  File "C:\ProgramData\miniconda3\lib\site-packages\paramiko\_winapi.py", line 176, in write
    dest = self.view + self.pos
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### Desktop (please complete the following information):
 - OS: [e.g. Ubuntu 22.04, Mac OS 12.5, Windows 11, etc.]

Windows 10

**Comment by KihoCho0627** [comment]
If I use command without GPU allocation like:
mila code Research/DomainGeneralization

Then VS code works.
