### ISSUE TITLE
[v0.0.18] Issue running the command `mila code`

### ISSUE THREAD

**Issue by AnnneRose** [mila-iqia/milatools#45]
### Make sure you can reproduce the issue with the latest version available
```
pip install milatools --upgrade
[milatools command e.g. mila code ...]
```

### What command did you run?
mila code /home/mila/a/annabel.adeyeri/ --alloc --cpus-per-task=2 --mem=4Gb --gres=gpu:1

### Describe the bug
A clear and concise description of what the bug is. If there is an error
traceback, please paste it here.
Traceback (most recent call last):
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/milatools/cli/commands.py", line 43, in main
    auto_cli(milatools)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/coleo/cli.py", line 656, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/Users/annabel/miniconda3/lib/python3.10
<img width="750" alt="Screenshot 2023-06-29 at 10 47 02 AM" src="https://github.com/mila-iqia/milatools/assets/50593284/444c5824-bffb-4d8e-ba93-2742579ebe1d">
/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/milatools/cli/commands.py", line 285, in code
    remote = Remote("mila")
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/milatools/cli/remote.py", line 84, in __init__
    connection.open()
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/fabric/connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/paramiko/client.py", line 485, in connect
    self._auth(
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/paramiko/client.py", line 818, in _auth
    raise saved_exception
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/paramiko/client.py", line 794, in _auth
    self._transport.auth_publickey(username, key)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/paramiko/transport.py", line 1658, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/Users/annabel/miniconda3/lib/python3.10/s
<img width="750" alt="Screenshot 2023-06-29 at 10 47 02 AM" src="https://github.com/mila-iqia/milatools/assets/50593284/d51c2afa-3c11-4404-8473-602df1bb5f9c">
ite-packages/paramiko/auth_handler.py", line 248, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed: transport shut down or saw EOF

### Desktop (please complete the following information):
 - Mac OS 13.4

### Additional context
it was working yesterday. idk what the problem is now.

**Comment by breuleux** [comment]
I believe there was an issue with logging in to the cluster in general this morning. Is the problem still happening? You can try to run `ssh mila` to check, if that doesn't work either then the issue is not with `mila code`.

**Comment by AnnneRose** [comment]
Hi!

I think the problem is resolved now.

Best,
Annabel Adeyeri
