### ISSUE TITLE
[v0.0.18] Issue running the command `mila code`

### ISSUE THREAD

**Issue by AnnneRose** [mila-iqia/milatools#46]
### Make sure you can reproduce the issue with the latest version available
```
pip install milatools --upgrade
[milatools command e.g. mila code ...]
```

### What command did you run?
[e.g. `mila code ...`]

### Describe the bug
A clear and concise description of what the bug is. If there is an error
traceback, please paste it here.
can't open mila code
Traceback (most recent call last):
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/milatools/cli/commands.py", line 43, in main
    auto_cli(milatools)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/coleo/cli.py", line 656, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/milatools/cli/commands.py", line 291, in code
    data, proc = cnode.ensure_allocation()
  File "/Users/annabel/miniconda3/lib/python3.10/site-packages/milatools/cli/remote.py", line 271, in ensure_allocation
    node_name = get_first_node_name(results["node_name"])
KeyError: 'node_name'
### Screenshots
<img width="787" alt="Screenshot 2023-06-29 at 12 55 52 PM" src="https://github.com/mila-iqia/milatools/assets/50593284/e973e572-f901-4055-be7d-a67c2c613258">

### Desktop (please complete the following information):
Mac OS 13.4

**Comment by breuleux** [comment]
The `salloc` message states `Prolog failure on node cn-b001`, which I believe usually indicates there is an issue with that particular node. Try again, possibly adding `-x cn-b001` to make sure it picks a different node.
