### ISSUE TITLE
Unable to install milatools with Poetry 

### ISSUE THREAD

**Issue by lebrice** [mila-iqia/milatools#81]
Seems like the `sshconf` package isn't setup to support PEP517 build. Perhaps we need to replace that package with a fork?
Alternatively we could not use Poetry? Any other solutions?

### Make sure you can reproduce the issue with the latest version available
```
pip install milatools --upgrade
[milatools command e.g. mila code ...]
```

### What command did you run?

```
conda create -n milatools python=3.11
conda activate milatools
pip install poetry
poetry install
```

### Describe the bug
A clear and concise description of what the bug is. If there is an error
traceback, please paste it here.

```
$ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing sshconf (0.2.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  <string>:3: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          ********************************************************************************
  
  !!
  /tmp/tmpshx_m0_f/.venv/bin/python: No module named pip
  Traceback (most recent call last):
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
      subprocess.check_call(cmd)
    File "/home/fabricenormandin/miniconda3/envs/milatools/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/tmpshx_m0_f/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp7j21z310', '--quiet', 'versiontag']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/home/fabricenormandin/miniconda3/envs/milatools/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/fabricenormandin/miniconda3/envs/milatools/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/fabricenormandin/miniconda3/envs/milatools/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 480, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 3, in <module>
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 636, in fetch_build_eggs
      return _fetch_build_eggs(self, requires)
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
      dist = self._resolve_dist(
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
      dist = best[req.key] = env.best_match(
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in best_match
      return self.obtain(req, installer)
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1147, in obtain
      return installer(requirement)
    File "/tmp/tmpshx_m0_f/.venv/lib/python3.10/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/tmp/tmpshx_m0_f/.venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp7j21z310', '--quiet', 'versiontag']' returned non-zero exit status 1.
  

  at ~/miniconda3/envs/milatools/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with sshconf (0.2.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "sshconf (==0.2.2)"'.
```

### Desktop (please complete the following information):
Ubuntu 20.04 LTS

**Comment by lebrice** [comment]
nevermind, was using an outdated version of the master branch (v0.0.7)
