### ISSUE TITLE
[v0.0.18] Issue running the command `mila code`

### ISSUE THREAD

**Issue by lezhang7** [mila-iqia/milatools#88]
### Make sure you can reproduce the issue with the latest version available
```
pip install milatools --upgrade
[milatools command e.g. mila code ...]
```

### What command did you run?
`mila code /home/mila/l/le.zhang/scratch/ --node cn-g027`

### Describe the bug

i can't connect vscode to a compute node

`Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/milatools/cli/commands.py", line 43, in main
    auto_cli(milatools)
  File "/opt/anaconda3/lib/python3.9/site-packages/coleo/cli.py", line 656, in auto_cli
    result = run_cli(entry, args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/coleo/cli.py", line 628, in run_cli
    return call(opts=opts, args=args)
  File "/opt/anaconda3/lib/python3.9/site-packages/coleo/cli.py", line 587, in thunk
    result = fn(*args)
  File "/opt/anaconda3/lib/python3.9/site-packages/milatools/cli/commands.py", line 288, in code
    cnode = _find_allocation(remote, job_name="mila-code")
  File "/opt/anaconda3/lib/python3.9/site-packages/milatools/cli/commands.py", line 699, in _find_allocation
    return Remote(node_name)
  File "/opt/anaconda3/lib/python3.9/site-packages/milatools/cli/remote.py", line 84, in __init__
    connection.open()
  File "/opt/anaconda3/lib/python3.9/site-packages/fabric/connection.py", line 636, in open
    self.client.connect(**kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/opt/anaconda3/lib/python3.9/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/opt/anaconda3/lib/python3.9/site-packages/paramiko/client.py", line 742, in _auth
    self._transport.auth_publickey(username, key)
  File "/opt/anaconda3/lib/python3.9/site-packages/paramiko/transport.py", line 1635, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/opt/anaconda3/lib/python3.9/site-packages/paramiko/auth_handler.py", line 259, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.`

### Desktop (please complete the following information):
 - OS: macOS 14.0 (23A344) M1 Pro

**Comment by lebrice** [comment]
Hey there. Are you still having issues? If so, feel free to comment or ping me on Slack. Closing this otherwise.
